name: Build and Push Assets

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Check for build changes
      id: check_changes
      run: |
        git add build/
        if git diff --cached --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit build assets
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git commit -m "chore: update build assets [skip ci]"
        git push origin main
    
    - name: No changes detected
      if: steps.check_changes.outputs.changes == 'false'
      run: echo "No changes in build assets detected, skipping commit"